action: {
  auto_create_index: false,
  destructive_requires_name: true
}

network: {
  host: 0.0.0.0
}

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery: {
  zen: {
    minimum_master_nodes: 1
  }
}

http: {
  cors: {
    enabled: false
  }
}

rest: {
  action: {
    multi: {
      allow_explicit_index: false
    }
  }
}

script: {
  inline: false,
  stored: false,
  file: false,
  engine: {
    groovy: {
      file: true
    }
  }
}
